### ISSUE TITLE
LiveChat - Flow of the conversation has changed

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#297] opened 2019-05-28 04:09 UTC
In the latest version V1.6.0, the conversations saved as test cases through live chat are showing up in the order bot first and user next in the convo file as below:

 NAMEOFCONVERSATION
 #bot default
 response

 #me
 Hi

 Till the last version, it was like user conversation showing up first and the bot next in an order. 

Is this a feature or bug or any setting to change this view?

**Comment by codeforequity-at** [comment] 2019-05-28 07:17
This is a bug, it already has been filed under BOT-629. There will be a hotfix release 1.6.1 in the next days.

**Comment by ujja** [comment] 2019-05-28 08:58
It is a bug, but i cant reproduce it. Which connector do you use? Could you test an other connector? (Like the simple echo connector, what I have use.)

**Comment by codeforequity-at** [comment] 2019-08-02 08:33
Fixed with Botium Box 1.6.1

**Closed** 2019-08-02 08:33 UTC
Labels: bug
