### ISSUE TITLE
Placeholders are not working even after enabling the SCRIPTING_ENABLE_MEMORY as true

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#261] opened 2019-04-03 10:18 UTC
While trying to add a placeholder for an dynamic value from the bot( date in the format 2019-04-03 09:38:52) by enabling the SCRIPTING_ENABLE_MEMORY as true and replaced the value in the convo file with the $now (as in Scripting memory system variables referred from the https://github.com/codeforequity-at/botium-core/wiki/Botium-Scripting)
It is not getting matched with the bot's updated time but rather it remains as a text like "$now" in the output.

**Comment by codeforequity-at** [comment] 2019-04-03 10:26
This is a very new feature, only available in the very latest build, so please first check if you are using the latest version.

**Comment by Aishwarya-J-S** [comment] 2019-04-03 10:37
It is working for the numerical values like "5". But not working for the dates

**Comment by Aishwarya-J-S** [comment] 2019-04-03 10:41
This is the version details:
Build Target: basic
Build Branch: master
Build Revision: 11669459a6f465e528afc82ee78c4b6c8d57f4df
Build Date: 2019-01-18T20:15:40+0000

**Comment by codeforequity-at** [comment] 2019-04-03 10:48
Please update to the latest release (1.4.0)

**Comment by Aishwarya-J-S** [comment] 2019-04-03 10:52
Thank you..I will update and let you know if it works

**Comment by Aishwarya-J-S** [comment] 2019-04-03 12:28
Updated to the following version and still facing the same issue

Build Target: basic
Build Branch: release/1.4.0
Build Revision: 4a101e74173a039d425bc70ede3542288cef1897
Build Date: 2019-03-31T22:00:00+02:00

**Comment by Aishwarya-J-S** [comment] 2019-04-04 03:29
The placeholder feature is not working in the Release 1.4.0 . Please help me on how to make the placeholder work for the date

**Comment by ujja** [comment] 2019-04-04 05:25
could you send verbose logs without sensitive info? (--verbose)

and your convo?

**Comment by Aishwarya-J-S** [comment] 2019-04-04 05:56
Following is the pattern of my convo file:

incident_check_01 
#me
Check Incident

#bot
Please provide incident number

#me
INCXXXXXX

#bot
Please find incident details below: <br>Number: <a href=https://link target="_blank" style="color:blue">INCXXXXX</a><br>Description: 7zip is not working properly in my computer<br>Caller: YYYY<br>Priority: Critical<br>Status: In Progress<br>Category: Software Issue<br>Updated on: $now UTC<br>Let me know if there is anything else you are looking for?


Can you please tell me how to take the verbose logs from botium box 1.4.0 which i am running with docker-compose?

**Comment by Aishwarya-J-S** [comment] 2019-04-04 06:00
![botium](https://user-images.githubusercontent.com/49233293/55532857-f974a880-56cc-11e9-8b13-86ea5004aed6.png)
Please find the additional settings added in the Bot

**Comment by codeforequity-at** [comment] 2019-04-05 06:53
What you want to achieve is currently not supported by the Scripting Memory - but it pointed us in a direction we want to deliver additional functionality soon. Don't ask for a date, it's in our backlog now and priorization depends on other open issues.
For now, what you could do is to add your own Asserter logic to validate the date of the bot response:
https://github.com/codeforequity-at/botium-core/tree/master/samples/extensions/asserterHooks

**Comment by Aishwarya-J-S** [comment] 2019-04-05 07:09
May I know what the Scripting Memory currently support? As per the documentation, as in the https://github.com/codeforequity-at/botium-core/wiki/Botium-Scripting, **Scripting memory system variables**, how this feature works?

**Comment by codeforequity-at** [comment] 2019-04-05 07:12
They are usable for adding dynamic content to the #me section (something is sent to the bot).

**Comment by Aishwarya-J-S** [comment] 2019-04-05 07:15
But it worked for this case when used in the #bot section below

#me
HTB000000000812

#bot
Hey, Your Bandwidth Details are:<br><br>Anytime Bandwidth: <b>XXXXXX</b> and Anytime Remaining Bandwidth: <b>XXXX</b>.<br>Bonus Bandwidth: <b>XXXXXXX</b> and Bonus Remaining Bandwidth: <b>12000 MB</b>.<br><br>You have <b>$days days</b> remaining to refill.<br><br>Is there any thing else that I can help you with?

**Comment by codeforequity-at** [comment] 2019-04-05 07:56
Yes, it partly works in these cases, but this is more by chance (or maybe even a bug). We will support your case very soon, asserting dynamic content is a high priority thing for us.

**Comment by davideaurucci** [comment] 2019-05-13 11:06
Does the SCRIPTING_ENABLE_MEMORY work also with Utterances for botium-cli? For example if I write:

#me 
$PROBLEM

#bot 
I understand you have the following issue: $PROBLEM. I will help you

where PROBLEM contains:
1) I have a issue with X
2) I have a issue with Y.

At the moment it doesn't really work (I have set SCRIPTING_ENABLE_MEMORY to TRUE in my JSON file). I am using Watson and excel files as input.

**Comment by codeforequity-at** [comment] 2019-05-13 11:24
It works with Botium-CLI as well, as this is a Botium Core feature.
However, Botium utterances and scripting memory are different concepts.

You should have a file utt_problem.utterances.txt:

    UTT_PROBLEM
    I have a issue with X
    I have a issue with Y

And the convo file like this: problem.convo.txt:

    problem
    
    #me
    UTT_PROBLEM
    
    #bot
    I understand you have the following issue: 
    
The scripting memory cannot be used in this case, as it is just matching single words, not whole sentences
You can find some docs about the scripting memory here: 
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities#SCRIPTING_MEMORY_MATCHING_MODE
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/26411023/Botium+Scripting+Memory

**Comment by DavidGarciaMoran** [comment] 2019-06-06 08:24
Hello, we are trying to train a dialog flow bot, and tried the Scripting memory feature, to test the different intents from dialog flow, and bot answers are utterances, that works fine. 
We are using botium box web, but the problem is that the scripting memory variables from file(with excell file, one sheet), are not detected, I want to know if this is botium box problem or dialog flow connector problem and if it could be resolved soon.

**Comment by Aishwarya-J-S** [comment] 2019-07-02 07:17
I am trying to keep the placeholders in the latest enterprise version of the botium where I wanted to put a placeholder for half of the conversation. How can it be implemented?

Also I have tried to keep the placeholders for the url and ticket number which is not working?

Can you please tell me how it can be done?

**Comment by codeforequity-at** [comment] 2019-07-02 07:56
Are you using the latest 1.7.2 build of the enterprise ?

**Comment by Aishwarya-J-S** [comment] 2019-07-05 06:33
Yeah now i have taken the latest 1.7.2 EE. How can  put a placeholder for a part of bot response after enabling the scripting memory?
**For Example** : If the response from bot is 
Please find details below: _some two line text here_. Let me know if there is anything else you are looking for?

How can I put the placeholder for second part of conversation as
Please find details below: _$details_. Let me know if there is anything else you are looking for?

**Comment by codeforequity-at** [comment] 2019-07-06 22:28
I consider this to be a bug. I will update this thread as soon as there is a solution available.

**Comment by ujja** [comment] 2019-07-12 07:58
will be fixed in next release. You have to set [SCRIPTING_MEMORY_MATCHING_MODE to joker](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities#SCRIPTING_MEMORY_MATCHING_MODE):

**Closed** 2019-07-12 07:59 UTC
Labels: enhancement
