### ISSUE TITLE
reset command at the top of convo file for chatbot reset is not working for directline3

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#119] opened 2018-10-03 08:28 UTC
If any of the test case failed, chatbot does not get reset and all remaining test cases gets failed. Any workaround for this?
Is there any way that I can apply a condition through code saying that if test case fails then exit from chatbot conversation. So that new test case will start conversation from scratch.

Note: I used reset command at the top of convo file. It worked with FBdirect container mode in Botium CLI.But not working with Directline. For some reason now I am using directline. So please suggest solution.

**Comment by codeforequity-at** [comment] 2018-10-03 09:15
From Botium side, every conversations starts from scratch. But as you already noticed with FB Direct, Facebook itself stores a state. This might be the same case for directline, but it really depends on the implementation - so I am curious why the approach with the "reset" command doesn't work - it should instruct the chatbot code to remove any session related data.

What might be the problem is that services like MS  Bot Framework store the conversation state by user, and that Botium on the other side uses the same user name for all conversations ("me") - so an obvious fix for this would be to add some variation here, and make Botium use different user names for each conversation, forcing Bot Framework (or other ones) to ignore existing user conversations and session information on running test cases.

**Comment by DipaliK9** [comment] 2018-10-03 10:02
I tried using different user name per conversation. But that didnt work. Also I realized lateron that reset is not working with fbdirect too. I am using Latest version of botium cli(0.0.22). 
Please refer convo.txt file as given below and let me know if I am missing anything.

File Name: Test.convo.txt

```
TestcaseName
reset

#User1
Ref_GETTING_STARTED

#bot default
Hi,

#bot default
Welcome to Chatbot

........
````

**Comment by codeforequity-at** [comment] 2018-10-03 10:11
This won't work for sure, as the "#User1" isn't currently recognized by Botium (in fact, the conversation should fail with because of this). There is some coding required for supporting variations in the username, this feature has to be added to Botium first.
The "reset" command above is not sent to the chatbot, as it has to be part of a user statement. Did you adapt your chatbot webhook to handle the "reset" text ?


```
TestcaseName

#me
reset

#me
Ref_GETTING_STARTED

#bot
Hi

#bot
...

```

**Comment by codeforequity-at** [comment] 2018-10-03 10:37
With botium-cli this is currently not possible. Botium-cli is based on Mocha. With Mocha it is possible to do so with the "bail" option (fail whole test suite on first test failure), but currently there is no way of running Botium-cli with this option. Would be a good enhancement though.
I would suggest to switch to the the companion project "testmybot"- it is based on Botium, just like the Botium-cli, but you are more flexible - testmybot converts the Botium convo scripts to Mocha test cases. There are several samples available. The downside is that you will have to install Node.js, NPM and you have to work with Mocha test runner directly.

**Comment by DipaliK9** [comment] 2018-10-03 10:40
I have testmybot, node.js and npm installed. If I use npm run command to execute cases, will it reset the chatbot. Can you pls help how can I make that happen using testmybot.

**Comment by codeforequity-at** [comment] 2018-10-03 10:47
The testmybot project contains some samples in the github repo - samples/mocha for example. It includes a package.json file with some scripts showing how to run mocha. If you add the "--bail" option there, the test suite will immediately exit on first failure.

**Comment by codeforequity-at** [comment] 2018-10-05 14:03
I am afraid the problem you describe is far too specific to be supported. All Botium can do for you is to send something to your bot and verify the response, at least when using it in this way.
In your case, it would require some coding - run the test cases one after the other, check the result of the last one, only reset when it failed ...
Without any knowledge on your bot implementation, I have the strong feeling that this is something to be solved in your chatbot code.

**Closed** 2018-12-27 09:48 UTC
Labels: enhancement
