### ISSUE TITLE
Directline attachments don't work anymore

### ISSUE THREAD

**Issue by alopix** [codeforequity-at/botium-core#405] opened 2019-10-08 09:30 UTC
**Describe the bug**
Trying to upload an attachment using the latest version of the directline connector does not work anymore.
The emulator will send an error back that `path is not available in unknown`.
Downgrading to one older version will make it work again.

**To Reproduce**
Use MEDIA with a directline convo and connect to a local bot through the botframework emulator.

**Expected behavior**
Upload works and `id` for attachment is being returned.

**Screenshots and Log files**

**Botium Flavour:**
 - Botium Box -
 - Botium CLI -
 - Botium Bindings 2.0.18
 - DL 0.0.15

**Botium Version**
1.6.1

**Additional context**

**Comment by codeforequity-at** [comment] 2019-10-08 09:40
Is it possible that the botframework emulator is behaving different than the real azure bot service ? We are using the Bot Framework MockBot for testing the connector features in Botium Box, and the attachment upload (at least for PNG pictures) is working there

**Comment by alopix** [comment] 2019-10-08 09:43
I'm not sure what exactly changed in your last connector code, but whatever change it is, I expect the file not being properly uploaded anymore?!

I would not expect the official emulator to really behave any differently, but it might – probably requires involving Microsoft in the comms.

**Comment by codeforequity-at** [comment] 2019-10-09 06:37
hm, I had to do some changes to make it work with the azure service - I had to add the mime type of the attachment, and I just noticed that this is a constant value "image/png" - not the best choice ...

**Comment by codeforequity-at** [comment] 2019-10-09 11:20
Can you tell me your setup, or point me to a source where your setup is described - I am not an expert in Bot Framework ... I want to try to reproduce it in my dev environment before doing anything for fixing it ...

**Comment by codeforequity-at** [comment] 2019-10-09 14:41
Thanks. I am always receiving the same error message in the Bot Framework Emulator - "Cannot read property 'name' of undefined" with the previous connector version, "Cannot read property 'path' of undefined" with the current connector version.

What version of the connector and the Bot Framework Emulator did work for you ? (I download the latest one 4.5.2)

**Comment by codeforequity-at** [comment] 2019-10-09 14:53
Yes, I know that this combination doesn't work ... but the 0.0.14 version of the connector doesn't work as well for me ...

I am trying to debug the Bot Framework Emulator to find the root cause

**Comment by alopix** [comment] 2019-10-09 15:04
I have no issue using 0.0.14.
```➜  directline_attachments_botium yarn test:botium
yarn run v1.19.1
$ jest
 PASS  spec/convo.spec.js
  custom_hooks_stop_working
    ✓ login with custom hook (2018ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.68s
Ran all test suites.
✨  Done in 6.58s.
➜  directline_attachments_botium ```

**Comment by codeforequity-at** [comment] 2019-10-09 16:15
Now this is a nice one. What I found out:

* It seems as if node-fetch 2.5.1 cannot handle the _Content-Type_ header correctly, as compared to 2.3.3 (dependency was updated with 0.0.15). Didn't dive into detail, but removing this header when uploading the attachment helped.
* And with node-fetch 2.5.1 somehow the response handling changed, I had to rewrite two code lines - you are working with local file attachments, so this was not the problem in your case.
* The Bot Framework Emulator requires an activity for the file upload - the Azure bot service does not. But both of them are fine with an empty activity, if no text is given in Botium.

The pull request is there, and it will be merged with the October release. Maybe you can check out the branch and test it: https://github.com/codeforequity-at/botium-connector-directline3/pull/31

**Comment by alopix** [comment] 2019-10-10 08:05
Oh, that is quite an interesting – quite an annoying issue with fetch.
I tried he branch and it worked as expected. Thanks 👍🏼

**Closed** 2019-11-12 20:18 UTC
Labels: bug
